name: Torture
version: 1.0.1
main: me.server.torturewatcher.Torture
api-version: 1.21
softdepend: [AuthMe]
commands:
  torture:
    description: Toggle torture for a player
    usage: /torture <player> <true|false>